version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/berserktech/telebot
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: go build
      - save_cache:
          key: dependency-cache
          paths:
            - "/go/pkg"
      - run:
          name: test
          command: go test
