version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: go mod download
      - save_cache:
          key: dependency-cache
          paths:
            - "/go/pkg"
      - run:
          name: tests
          command: go test ./... 
      - run:
          name: fmt
          command: ./fmt-check.bash 
